import type { SiteAsset } from "@/content/types";

export const siteAssets: SiteAsset[] = [
  {
    name: "favicon-tilda",
    sourceUrl: "https://static.tildacdn.net/img/tildafavicon.ico",
    localPath: "/assets/favicon/tildafavicon.ico",
    usage: "site favicon",
    notes: "Default favicon exported from the current Tilda site.",
  },
  {
    name: "kubera-logo-main",
    sourceUrl: "local",
    localPath: "/assets/logo/kubera-ai-logo-source.png",
    usage: "primary brand logo",
    notes: "User-provided black/gold logo with KUBERA AI text and Living Systems subtitle.",
  },
  {
    name: "arrow-right",
    sourceUrl: "https://static.tildacdn.net/lib/icons/button/widearw_right_regular.svg",
    localPath: "/assets/icons/widearrow-right-regular.svg",
    usage: "CTA icon",
    notes: "Tilda button arrow icon.",
  },
  {
    name: "customer-communications-icon",
    sourceUrl: "https://static.tildacdn.net/tild3134-3337-4637-b165-303037653138/vector.svg",
    localPath: "/assets/icons/tilda-vector-3134.svg",
    usage: "services page",
    notes: "Custom Tilda vector icon used in services blocks.",
  },
  {
    name: "sales-leads-icon",
    sourceUrl: "https://static.tildacdn.net/tild3232-3737-4039-b462-643665383532/vector.svg",
    localPath: "/assets/icons/tilda-vector-3232.svg",
    usage: "services page",
    notes: "Custom Tilda vector icon used in services blocks.",
  },
  {
    name: "internal-processes-icon",
    sourceUrl: "https://static.tildacdn.net/tild6237-3134-4962-a636-393437666262/vector.svg",
    localPath: "/assets/icons/tilda-vector-6237.svg",
    usage: "services page",
    notes: "Custom Tilda vector icon used in services blocks.",
  },
  {
    name: "hr-hiring-icon",
    sourceUrl: "https://static.tildacdn.net/tild6365-3263-4638-a335-636536653066/vector.svg",
    localPath: "/assets/icons/tilda-vector-6365.svg",
    usage: "services page",
    notes: "Custom Tilda vector icon used in services blocks.",
  },
  {
    name: "content-marketing-icon",
    sourceUrl: "https://static.tildacdn.net/tild6563-3462-4535-b837-383938386331/vector.svg",
    localPath: "/assets/icons/tilda-vector-6563.svg",
    usage: "services page",
    notes: "Custom Tilda vector icon used in services blocks.",
  },
  {
    name: "finance-documents-icon",
    sourceUrl: "https://static.tildacdn.net/lib/icons/tilda/-/paint/c9a84c--1-0-100/accountant_calculator.svg",
    localPath: "/assets/images/services/accountant-calculator.svg",
    usage: "services page",
    notes: "Full-size static Tilda CDN SVG service icon.",
  },
  {
    name: "ecommerce-logistics-icon",
    sourceUrl: "https://static.tildacdn.net/lib/icons/tilda/-/paint/c9a84c--1-0-100/trade_in.svg",
    localPath: "/assets/images/services/trade-in.svg",
    usage: "services page",
    notes: "Full-size static Tilda CDN SVG service icon.",
  },
  {
    name: "education-icon",
    sourceUrl: "https://static.tildacdn.net/lib/icons/tilda/-/paint/c9a84c--1-0-100/student_graduate_teacher.svg",
    localPath: "/assets/images/services/student-graduate-teacher.svg",
    usage: "services page",
    notes: "Full-size static Tilda CDN SVG service icon.",
  },
  {
    name: "real-estate-icon",
    sourceUrl: "https://static.tildacdn.net/lib/icons/tilda/-/paint/c9a84c--1-0-100/house_flat.svg",
    localPath: "/assets/images/services/house-flat.svg",
    usage: "services page",
    notes: "Full-size static Tilda CDN SVG service icon.",
  },
  {
    name: "hotels-restaurants-icon",
    sourceUrl: "https://static.tildacdn.net/lib/icons/tilda/-/paint/c9a84c--1-0-100/house_building.svg",
    localPath: "/assets/images/services/house-building.svg",
    usage: "services page",
    notes: "Full-size static Tilda CDN SVG service icon.",
  },
  {
    name: "transport-logistics-icon",
    sourceUrl: "https://static.tildacdn.net/lib/icons/tilda/-/paint/c9a84c--1-0-100/route_map_road.svg",
    localPath: "/assets/images/services/route-map-road.svg",
    usage: "services page",
    notes: "Full-size static Tilda CDN SVG service icon.",
  },
  {
    name: "beauty-health-icon",
    sourceUrl: "https://static.tildacdn.net/lib/icons/tilda/-/paint/c9a84c--1-0-100/hairstyle_girl.svg",
    localPath: "/assets/images/services/hairstyle-girl.svg",
    usage: "services page",
    notes: "Full-size static Tilda CDN SVG service icon.",
  },
  {
    name: "medical-clinics-icon",
    sourceUrl: "https://static.tildacdn.net/lib/icons/tilda/-/paint/c9a84c--1-0-100/pregnant_obstetrics.svg",
    localPath: "/assets/images/services/pregnant-obstetrics.svg",
    usage: "services page",
    notes: "Full-size static Tilda CDN SVG service icon.",
  },
  {
    name: "auto-business-icon",
    sourceUrl: "https://static.tildacdn.net/lib/icons/tilda/-/paint/c9a84c--1-0-100/car_warehouse_cargo.svg",
    localPath: "/assets/images/services/car-warehouse-cargo.svg",
    usage: "services page",
    notes: "Full-size static Tilda CDN SVG service icon.",
  },
  {
    name: "workflow-calendar-icon",
    sourceUrl: "https://static.tildacdn.net/lib/icons/tilda/-/paint/c9a84c--1-0-100/calendar_date_day.svg",
    localPath: "/assets/images/services/calendar-date-day.svg",
    usage: "how we work page",
    notes: "Full-size static Tilda CDN SVG process icon.",
  },
  {
    name: "workflow-gear-icon",
    sourceUrl: "https://static.tildacdn.net/lib/icons/tilda/-/paint/c9a84c--1-0-100/gear_settings.svg",
    localPath: "/assets/images/services/gear-settings.svg",
    usage: "how we work page",
    notes: "Full-size static Tilda CDN SVG process icon.",
  },
  {
    name: "workflow-puzzle-icon",
    sourceUrl: "https://static.tildacdn.net/lib/icons/tilda/-/paint/c9a84c--1-0-100/puzzle_game.svg",
    localPath: "/assets/images/services/puzzle-game.svg",
    usage: "how we work page",
    notes: "Full-size static Tilda CDN SVG process icon.",
  },
  {
    name: "workflow-vector-6230",
    sourceUrl: "https://static.tildacdn.net/tild6230-6533-4235-a438-396164396463/vector.svg",
    localPath: "/assets/icons/tilda-vector-6230.svg",
    usage: "how we work page",
    notes: "Custom Tilda vector icon used in process blocks.",
  },
  {
    name: "workflow-vector-6339",
    sourceUrl: "https://static.tildacdn.net/tild6339-3063-4632-b663-663035356530/vector.svg",
    localPath: "/assets/icons/tilda-vector-6339.svg",
    usage: "how we work page",
    notes: "Custom Tilda vector icon used in process blocks.",
  },
  {
    name: "landing-page-gpt-nti-icon",
    sourceUrl: "local",
    localPath: "/assets/icons/landing-page-gpt-nti.svg",
    usage: "services page",
    notes: "Local visual placeholder for the new Landing Page GPT-NTI service.",
  },
  {
    name: "case-dashboard-579c724",
    sourceUrl: "https://static.tildacdn.net/tild3465-3030-4464-a632-666535633561/file_00000000579c724.png",
    localPath: "/assets/images/cases/case-dashboard-579c724.png",
    usage: "cases page",
    notes: "Full-size Tilda CDN image; thumbnail variant was skipped.",
  },
  {
    name: "case-dashboard-31b871f",
    sourceUrl: "https://static.tildacdn.net/tild3866-6138-4563-b065-633534363865/file_0000000031b871f.png",
    localPath: "/assets/images/cases/case-dashboard-31b871f.png",
    usage: "cases page",
    notes: "Full-size Tilda CDN image; thumbnail variant was skipped.",
  },
  {
    name: "case-dashboard-1f8c724",
    sourceUrl: "https://static.tildacdn.net/tild3963-3639-4237-b236-376362343062/file_000000001f8c724.png",
    localPath: "/assets/images/cases/case-dashboard-1f8c724.png",
    usage: "cases page",
    notes: "Full-size Tilda CDN image; thumbnail variant was skipped.",
  },
  {
    name: "case-dashboard-947c724",
    sourceUrl: "https://static.tildacdn.net/tild6164-6635-4235-b165-363035393532/file_00000000947c724.png",
    localPath: "/assets/images/cases/case-dashboard-947c724.png",
    usage: "cases page",
    notes: "Full-size Tilda CDN image; thumbnail variant was skipped.",
  },
  {
    name: "case-dashboard-80a071f",
    sourceUrl: "https://static.tildacdn.net/tild6366-6233-4363-a165-366636306361/file_0000000080a071f.png",
    localPath: "/assets/images/cases/case-dashboard-80a071f.png",
    usage: "cases page",
    notes: "Full-size Tilda CDN image; thumbnail variant was skipped.",
  },
  {
    name: "case-dashboard-4ac0724",
    sourceUrl: "https://static.tildacdn.net/tild6631-3862-4336-a635-373630303239/file_000000004ac0724.png",
    localPath: "/assets/images/cases/case-dashboard-4ac0724.png",
    usage: "cases page and OG candidate",
    notes: "Full-size Tilda CDN image; thumbnail/og resized variants were skipped.",
  },
];

export const caseAssets = siteAssets.filter((asset) => asset.usage.includes("cases page"));

export function getAssetByName(name: string) {
  return siteAssets.find((asset) => asset.name === name);
}
