export const siteConfig = {
  name: "Kubera AI",
  legalName: "Kubera AI",
  url: "https://www.kubera-automation.com",
  description: "Living Systems. Smart Automation.",
  email: "hello@kubera-automation.com",
  phone: "+37253841877",
  telegram: "@kubera_automation",
  telegramUrl: "https://telegram.me/kubera_automation",
  whatsappUrl: "https://wa.me/37253841877",
  logo: "/assets/logo/kubera-ai-logo-source.png",
  defaultOgImage: "/assets/images/cases/case-dashboard-4ac0724.png",
  sameAs: ["https://telegram.me/kubera_automation", "https://wa.me/37253841877"],
};

export const supportedLanguages = {
  en: "English",
  ru: "Russian",
  es: "Spanish",
  de: "German",
  fr: "French",
  it: "Italian",
  nl: "Dutch",
  pt: "Portuguese",
  pl: "Polish",
  et: "Estonian",
  lv: "Latvian",
  lt: "Lithuanian",
  fi: "Finnish",
  sv: "Swedish",
  da: "Danish",
  uk: "Ukrainian",
};
